runtime: python39  # Spécifie la version de Python à utiliser

entrypoint: gunicorn -b :$PORT main:app  # Indique à App Engine d'exécuter le serveur Gunicorn

handlers:
- url: /.*
  script: auto  # Indique à App Engine d'exécuter le script Python correspondant à l'URL demandée